AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BirthdayTracker

  Sample SAM Template for BirthdayTracker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
Resources:
  birthdaytracker:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "birthdayTracker"
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: month
          AttributeType: N
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: "monthAndDateIndexName"
        KeySchema:
          - AttributeName: month
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
  BirthdayTrackerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: BirthdayTrackerFunction
      Handler: com.birthdaytracker.functions.InsertBirthdayDateLambda::handleRequest
      Runtime: java11
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref birthdayTracker
      Events:
        BirthdayTracker:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /createDate
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BirthdayTrackerApi:
    Description: "API Gateway endpoint URL for Prod stage for Birthday Tracker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getDate/"
  BirthdayTrackerFunction:
    Description: "Birthday Tracker Lambda Function ARN"
    Value: !GetAtt BirthdayTrackerFunction.Arn
  BirthdayTrackerFunctionIamRole:
    Description: "Implicit IAM Role created for Birthday Tracker function"
    Value: !GetAtt BirthdayTrackerFunctionRole.Arn
