AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  birthdayTrackerTableName:
    Type: String
    Default: "birthdaytracker"
    Description: "Name of the main table"
  monthToNameIndexName:
    Type: Number
    Default: "month-name-index"
    Description: "Name of the month-name index"
  dateToNameIndexName:
    Type: Number
    Default: "date-name-index"
    Description: "Name of the date-name index"
    AWS::DynamoDB::Table.
Resources:
  birthdaytracker:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: birthdayTrackerTableName
      AttributeDefinitions:
        -
          AttributeName: name
          AttributeType: S
        -
          AttributeName: Month
          AttributeType: N
        -
          AttributeName: date
          AttributeType: N
            KeySchema:
        -
          AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          -
            IndexName:
              Ref: monthToNameIndexName
            KeySchema:
              -
                AttributeName: month
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          -
            IndexName:
              Ref: dateToNameIndexName
            KeySchema:
              -
                AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

